apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iftop-exporter-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iftop-exporter-leader-election-role
subjects:
- kind: ServiceAccount
  name: iftop-exporter
  namespace: {{ template "iftop-exporter.namespace" . }}
